version: '3'

services:
  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '8080:8080' # expose 80 on host and sent to 80 in container
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd  # this will use httpd:latest
    # ports:
    #   - '80:8080'